name: Deploy to GitHub Pages

on:
  # mainブランチへのプッシュ時にデプロイ
  push:
    branches: ["main"]
  
  # 手動でワークフローを実行可能
  workflow_dispatch:

# GitHub Pagesへのデプロイに必要な権限
permissions:
  contents: write

jobs:
  # ビルド & デプロイジョブ
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
